### ISSUE TITLE
Improve versioning, triage milestones

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#247]
We're progressing on Amy nicely, but we don't track it: either in GitHub's milestones, or via project's version changes.

A to-do list:

* [x] adopt a versioning system ([semver.org](semver.org)?) - should be mentioned in CONTRIBUTING.md
* [ ] add `setup.py`? (so that we can store version somewhere)
* [x] set Amy to some version (0.9.0?) (in both `setup.py` and `bower.json`)
* [x] triage issues to milestones on GitHub
* [x] git-tag releases

**Comment by gvwilson** [comment]
1. +1 to semver
2. +1 to setup.py
3. Set version to 0.2 - after all, this will be our second trial run.
4. +1 to triage
5. +1 to tagging releases.

**Comment by wking** [comment]
On Sun, Apr 19, 2015 at 02:12:20AM -0700, Piotr Banaszkiewicz wrote:
> A to-do list…

All of these sound good to me, but before we get serious about package
management, I think we need to think a bit about clean boundaries
between our packages first.  My previous suggestions along these lines
include:

* Separate the workshops app (which is probably generically useful
  enough to push to PyPI) from our deploy-specific content (which
  nobody else will care about) [1].  This may take some refactoring
  because the current layout doesn't always distinguish between
  “provide a generic Person/Site/Event/… tracking module” and “deploy
  that module for SWC”, but I think we *should* make that distinction
  clear before pushing code to PyPI.

* Avoid bundling code like the workshop-check script, which I think
  should be pushed to PyPI independently, and then consumed by both
  Amy and workshop-template [2].

So I'd start this push towards packaging with the workshop-checkout
script (where it's nice and easy).  Once we get through that
unscathed, I'd shift into cutting out the workshops module with clean
margins (and likely a more specific name ;) and pushing *that* to
PyPI.  Then whatever we have left here (likely not much, just the
Makefile, Django config, logo, …) can just live in Git and maybe get
date-stamped releases when we deploy it to amy.software-carpentry.org.

[1]: https://github.com/swcarpentry/amy/pull/140#issuecomment-70738784
[2]: https://github.com/swcarpentry/amy/pull/111#issuecomment-68059757

**Comment by gvwilson** [comment]
Can this now be closed?

**Comment by pbanaszkiewicz** [comment]
Sure.
