### ISSUE TITLE
Review scripts and commands

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#605]
We probably don't need a lot of these scripts or commands. Check which ones are being used, and get rid of others.

(I'd like to not have any commands or scripts, because it's harder to maintain them.)

TODO:
* [X] remove `test-command-line-upload.sh` (done in #608)
* [X] remove `parse-instructor-info.py` (done in #608)
* [ ] update anonymizer or whole dev database (see #534)
* [ ] remove `mail-all-activity.py` and integrate content into `workshops/management/commands/report_all_instructor_activity.py` (see #629)
* [ ] examine other management commands in workshops/management/commands/* and remove those that are out of date or no longer needed (see #629)

**Comment by pbanaszkiewicz** [comment]
Added a TODO in the issue content.
